services:

  postgres:
    container_name: waa-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: waa
#      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend:
    container_name: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: host.docker.internal:5432
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  postgres:
  pgadmin: